apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    customLogoFile:
      key: arion-banki-logo.svg
      name: arion-banki-logo
    customProductName: My Console